spring.datasource.url=jdbc:postgresql://localhost:6565/Cosmic
spring.datasource.username=postgres
spring.datasource.password=thomas
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/Customer
server.port=8021
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tmj949474@gmail.com
spring.mail.password= wehf jtbh nbie psub
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
